FROM alpine:3.14.1

# Update apk repositories
RUN touch /etc/apk/repositories
RUN printf "http://dl-cdn.alpinelinux.org/alpine/v3.14/main\n" >> /etc/apk/repositories
RUN printf "http://dl-cdn.alpinelinux.org/alpine/v3.14/community\n" >> /etc/apk/repositories

RUN apk update

# Install Apache and PHP8
RUN apk add \
  apache2 \
  nodejs \
  npm

COPY ./conf.d/web/ /etc/
COPY ./web.init.sh /
RUN chmod +x /web.init.sh

# Define workdir and start apache daemon
WORKDIR "/var/www/localhost/htdocs"
CMD ["/web.init.sh"]
