version: '3'

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/localhost/htdocs
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - ./web:/var/www/localhost/htdocs
    depends_on:
      - php
