FROM alpine:3.14.1

# Update apk repositories
RUN touch /etc/apk/repositories
RUN printf "http://dl-cdn.alpinelinux.org/alpine/v3.14/main\n" >> /etc/apk/repositories
RUN printf "http://dl-cdn.alpinelinux.org/alpine/v3.14/community\n" >> /etc/apk/repositories

RUN apk update

# Install Apache and PHP
RUN apk add \
  apache2 \
  php8 \
  php8-curl \
  php8-apache2 \
  php8-pdo_mysql \
  php8-mbstring \
  php8-iconv \
  php8-dom \
  php8-xml \
  php8-xmlwriter \
  php8-fileinfo \
  php8-tokenizer \
  php8-phar \
  php8-session \
  php8-opcache

RUN mv /usr/bin/php8 /usr/bin/php

RUN mkdir /var/tmp/composer-installer \
  && cd /var/tmp/composer-installer \
  && php -r "readfile('https://getcomposer.org/installer');" \
  | php -- --install-dir=/usr/local/bin --filename=composer
RUN chmod +x /usr/local/bin/composer

COPY ./conf.d/api/ /etc/
COPY ./api.init.sh /
RUN chmod +x /api.init.sh

# Define workdir and start apache daemon
WORKDIR "/var/www/localhost/htdocs"
CMD ["/api.init.sh"]
