version: '3.9'

services:

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./docker/nginx/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - backend
      - pma
      - frontend

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sonet
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/my.cnf

  fpm:
    build: ./docker/php/
    container_name: fpm
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./backend:/var/www/html
    depends_on:
      - mariadb

  backend:
    image: nginx:alpine
    container_name: backend
    volumes:
      - ./docker/nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/backend/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/html
    depends_on:
      - fpm

  pma:
    image: phpmyadmin
    container_name: pma
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mariadb

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./docker/nginx/frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html
