version: '3'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sonet
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/my.cnf

  fpm:
    build: ./docker/php/
    container_name: fpm
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./server-side:/var/www/html
    depends_on:
      - cache
    depends_on:
      - mariadb

  server:
    image: nginx:alpine
    container_name: server
    volumes:
      - ./docker/nginx/server/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/server/nginx.conf:/etc/nginx/nginx.conf
      - ./server-side:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - fpm

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mariadb

  client:
    image: nginx:alpine
    container_name: client
    volumes:
      - ./docker/nginx/client/default.conf:/etc/nginx/conf.d/default.conf
      - ./client-side:/var/www/html
    ports:
      - 80:80
