<?php

namespace App\Modules\Sonet\Controllers;

use App\Modules\Sonet\Requests\StoreCategoryRequest;
use App\Modules\Sonet\Requests\UpdateCategoryRequest;
use App\Modules\Sonet\Resources\CategoryResource;
use App\Modules\Sonet\Resources\DeletedResource;
use App\Http\Resources\Exceptions\UnauthorizedResource;
use App\Modules\Sonet\Models\Category;
use App\Modules\Sonet\Models\User;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class CategoryController extends \App\Http\Controllers\Controller
{
    /**
     * Show all user's categories.
     *
     * @return AnonymousResourceCollection
     */
    public function index(): AnonymousResourceCollection
    {
        /** @var User $user */
        $user = Auth::user();

        return CategoryResource::collection($user->categories()->orderByDesc('order')->get());
    }

    /**
     * Show a specific category.
     *
     * @param Category $category
     */
    public function show(Category $category) {
        // TODO: Change the autogenerated stub.
    }

    /**
     * Store new user's category.
     *
     * @param StoreCategoryRequest $request
     * @return CategoryResource
     */
    public function store(StoreCategoryRequest $request): CategoryResource
    {
        $category = new Category($request->all());
        $category->save();

        return CategoryResource::make($category);
    }

    /**
     * Update the category.
     *
     * @param UpdateCategoryRequest $request
     * @param Category $category
     * @return CategoryResource|UnauthorizedResource
     */
    public function update(UpdateCategoryRequest $request, Category $category) {
        if (!Gate::check('update-category', $category)) return UnauthorizedResource::make();

        $category->update($request->all());

        return CategoryResource::make($category);
    }

    /**
     * Delete user's category.
     *
     * @param Category $category
     * @return DeletedResource
     */
    public function destroy(Category $category): DeletedResource
    {
        $category->delete();

        return DeletedResource::make();
    }
}
